version: '3.2'

services:
#elasticsearch_the version is defined in ./.env file
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - elk

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
    - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    
        

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
    - "2181"
    networks:
      - elk

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0

    ports:
    - "9092:9092"
    expose:
    - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      - elk
    depends_on:
    - zookeeper

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana
        
  kafka_elk_asamasach:
    build: .
    container_name: kafka_elk_asamasach
    volumes:
      - type: bind
        source: ./python_code/kafka_2_elk_asamasach.py
        target: /code/kafka_2_elk_asamasach.py
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kafka
    
volumes:
  zookeeper_data:
  kafka_data:
  elasticsearch:
  kafka_elk_asamasach:

networks:
  elk:
    driver: bridge    
